### ISSUE TITLE
Cannot read property 'startOfWeek' of undefined

### ISSUE THREAD

**Issue by rgnevashev** [intljusticemission/react-big-calendar#1042]
![2018-10-10_13-02-35](https://user-images.githubusercontent.com/123600/46729024-da9cd880-cc8c-11e8-9a9c-4c23f776b7fc.png)

https://github.com/intljusticemission/react-big-calendar/blob/fb5b346de58b0c3c50cf967df8b63efec5a21506/src/Month.js#L330

https://github.com/intljusticemission/react-big-calendar/blob/fb5b346de58b0c3c50cf967df8b63efec5a21506/src/Calendar.js#L895

Check passed secondary param..  localizer doesnt pass in handleRangeChange

**Comment by CodeXtinction** [comment]
yup i have the same issue

**Comment by gtaylor44** [comment]
I had this issue after upgrading from 0.19.2 to 0.20.2

import * as datesUtility from 'react-big-calendar/lib/utils/dates';

it looks like datesUtility.firstVisibleDay now takes the param 'localizer'.

Fixed by passing in localizer

const localizer = BigCalendar.momentLocalizer(moment);

datesUtility.firstVisibleDay(date, localizer)
