### ISSUE TITLE
Multiple events completely hidden by another event in Day/Week views

### ISSUE THREAD

**Issue by drewtonynguyen** [intljusticemission/react-big-calendar#1086]
#### Do you want to request a _feature_ or report a _bug_?

Bug.

#### What's the current behavior?

Using Big Calendar v0.20.1. step is 30, timeslots is 2.
Events are:

```
Event A: 1:00-3:00pm
Event B: 2:30-3:00pm
Event C: 3:00-4:30pm
Event D: 3:00-4:30pm
Event E: 4:00-5:30pm
Event F: 4:00-5:30pm
Event G: 4:30-6:00pm
Event H: 5:00-7:00pm
Event I: 5:30-7:00pm
Event J: 5:30-7:00pm
Event K: 5:30-7:00pm
```

I've been able to reproduce a rare case in which multiple overlapping events are hidden by a larger event. 

<img width="1108" alt="screen shot 2018-11-04 at 10 03 00 am" src="https://user-images.githubusercontent.com/41304160/47968232-c0e87a00-e01b-11e8-99f1-fcdabbfc1165.png">

As you can see, Events I and J are completely hidden by Event H.

I suspect it has something to do with the onSameRow function in ```DayEventLayout.js```:

```js
/**
 * Return true if event a and b is considered to be on the same row.
 */
function onSameRow(a, b, minimumStartDifference) {
  return (
    // Occupies the same start slot.
    Math.abs(b.start - a.start) < minimumStartDifference ||
    // A's start slot overlaps with b's end slot.
    (b.start > a.start && b.start < a.end)
  )
}
```

I see that in #910, there was a reversal in the direction of the comparison between a and b's start and end slots. However, if I add the original check back in and check both directions:

```js
function onSameRow(a, b, minimumStartDifference) {
  return (
    // Occupies the same start slot.
    Math.abs(b.start - a.start) < minimumStartDifference ||
    // A's start slot overlaps with b's end slot.
    (b.start > a.start && b.start < a.end) ||
    (a.start > b.start && a.start < b.end)
  )
}
```

I end up with the following layout of events:

<img width="1107" alt="screen shot 2018-11-04 at 10 02 37 am" src="https://user-images.githubusercontent.com/41304160/47968296-d90cc900-e01c-11e8-9b67-871d40037614.png">

As you can see, all events are now visible. Any thoughts, @bgelineau? Would checking a and b's time slots in both directions for the same row computation be the right fix here? I can make a PR to add the check back in if so.

#### What's the expected behavior?

All events should be shown.

**Comment by bgelineau** [comment]
Hi @drewtonynguyen, with your example, you are correct that a and b's times should be compared in both directions. However it has some unfortunate side-effects, like the perfectly correct : 

![one sided](https://user-images.githubusercontent.com/1941277/48005899-e60ce380-e114-11e8-9089-d3e4e800e2fa.png)

becoming 

![both sides](https://user-images.githubusercontent.com/1941277/48005922-edcc8800-e114-11e8-979c-ac6ac72259e0.png)

and

![2-1](https://user-images.githubusercontent.com/1941277/48006677-451f2800-e116-11e8-9c75-0a3857f26309.png)

becoming

![2-2](https://user-images.githubusercontent.com/1941277/48006682-494b4580-e116-11e8-96a1-ba56944c55f5.png)

From what I see, the problem stems from doing the computation of rows in the order given by sortByRender and not just in the order ('startMs', '-endMS').

@jquense : why the complex logic in https://github.com/intljusticemission/react-big-calendar/blob/master/src/utils/DayEventLayout.js#L105 given that the rows computation only require the first line? Is it to alternate the rendering between non-overlapping events of the same row like in the following screenshot in order to increase readability?

![alternate](https://user-images.githubusercontent.com/1941277/48008973-09d32800-e11b-11e8-9c08-4ac1352149dc.png)

I don't see another use case and it creates the problems told above, where we have to choose between two incorrect renderings (@drewtonynguyen's being less incorrect).

**Comment by drewtonynguyen** [comment]
Thanks @bgelineau. I tested changing the sortByRender method as so, removing the logic you mentioned:

```js
function sortByRender(events) {
  const sortedByTime = sortBy(events, ['startMs', e => -e.endMs])

  return sortedByTime
}
```

and my example now looks like:

![screen shot 2018-11-05 at 9 58 42 am](https://user-images.githubusercontent.com/41304160/48016840-93660400-e0e1-11e8-9297-713736b18d23.png)

**Comment by Dragomir-Ivanov** [comment]
@drewtonynguyen It looks much nicer with your solution. @bgelineau Is there any chance, we can make this an option, so people can actually choose their sorting behavior? I will allow uglier representation, over some hidden events.

Thanks, `react-big-calendar` is awesome!
