### ISSUE TITLE
Min with DST timeslot labels are incorrect

### ISSUE THREAD

**Issue by lilbumblebear** [intljusticemission/react-big-calendar#1098]
#### Do you want to request a _feature_ or report a _bug_? 
Bug

#### What's the current behavior?
When displaying events on calendar with min and max props set, the event is displayed in the correct spot, but the hour on the timeslot label is off by 1 hour (assuming this is DST related). 

[CodeSandbox](https://codesandbox.io/embed/8245oj6530)
<img width="961" alt="screen shot 2018-11-08 at 1 53 11 pm" src="https://user-images.githubusercontent.com/18397507/48220757-290dc780-e35e-11e8-9551-9d6b71e4e730.png">

#### What's the expected behavior?
I would expect the timeslot labels to have the correct time label based on whether you are currently in or out of Daylight Savings Time (DST).   I am looking through the source code to see if I can find the exact error.

**Comment by NuclearKev** [comment]
It seems like `max` has been fixed in version `0.20.2` on npm. `min` still not working correctly for me.

**Comment by lilbumblebear** [comment]
Thank you @NuclearKev, I checked and it does work if I don't have min set.   I have updated the issue title since max is resolved.

**Comment by lilbumblebear** [comment]
I noticed this appears to only be an issue for the week when DST changed.  I am assuming it has something to do with the extra hour on Sunday for the week view.  I haven't been able to find a solution yet.

**Comment by alastairjeremy** [comment]
I came across this problem with the 'min' prop set, and found that by localizing my calendar to have the week start on Monday, then the problem "went away" (I'm sure it's still there, but just not noticeable). Hopefully this helps identify where the problem lies!

Before:
const localizer = BigCalendar.momentLocalizer(moment);

After:
moment.locale("au", {
  week: {
    dow: 1,
    doy: 1
  }
});
const localizer = BigCalendar.momentLocalizer(moment);

My test period was the week that included Sunday 7th April 2019 in Australian timezone (which is the end of daylight savings), and I have a 'min' set like this:

const CALENDAR_MIN = new Date(1970, 6, 1, 6);
...
 <DragAndDropCalendar
...
 min={CALENDAR_MIN}
...

When the week started on Sunday, the problem was exactly as per screenshots. When the week started on Monday, then all was visibly OK.
