### ISSUE TITLE
Right click on the event display a menu

### ISSUE THREAD

**Issue by fengdachao** [intljusticemission/react-big-calendar#1113]
I hope to add right click callback. Thanks.

**Comment by dmitrykrylov** [comment]
@fengdachao use custom Event component and onContextMenu prop?

**Comment by PPepperCC** [comment]
I also want this functionality. Using custom event components doesn't work very well because the custom event component doesn't 'fill' the graphical event, so right clicking on parts of the event won't bring up a menu.

I'm using a very convoluted alternative approach, where the onContextMenu event handler is on the containing div of the calendar, then I'm using custom Event components with a data prop containing an ID, and some clunky DOM traversal to get that ID from the synthetic event which works, but is pretty ugly.

**Comment by jquense** [comment]
Happy to allow this via the eventPropGetter if anyone wants to add support for it there.

**Comment by nomrik** [comment]
We are also facing with a need for this capability, and I'll be happy to be open a PR.

@jquense - is there a reason why you would prefer this on the eventPropGetter, instead of adding an "onContextMenu" prop to EventCell.js, same as onDoubleClick and onClick?

Thanks!

**Comment by vzvu3k6k** [comment]
It may be helpful to set your custom `eventWrapper` like `<Calendar components={{ eventWrapper }} />`.

Here is an example: https://codepen.io/vzvu3k6k/pen/ewRGwW

**Comment by darkcattz** [comment]
Hello, 

Any news for this feature?

If I use the example above, it works but I get this error: 

`Warning: React.createFactory() is deprecated and will be removed in a future major release. Consider using JSX or use React.createElement() directly instead.
`

Thanks
