### ISSUE TITLE
how.to.gen one es5 minified bundle

### ISSUE THREAD

**Issue by e178551** [intljusticemission/react-big-calendar#1141]
#### Do you want to request a _feature_ or report a _bug_?
request
#### What's the current behavior?
there is no minified dist after building.

#### What's the expected behavior?
how can i get.minified js using es2015 preset?

**Comment by jquense** [comment]
you can use webpack, parcel or other bundler that understands commonjs modules to minify

**Comment by busybox11** [comment]
Hello,
I am currently trying to optimize my webpack bundle size.
It looks like moment is taking lots of space because of its locales.
I tried removing them with a simple plugin, `new webpack.IgnorePlugin(/^\.\/locale$/, /moment$/)`, but it didn't change my bundle size at all.
Is it a known behavior, and thus all the locales are required?
Thanks in advance and have a great day!

**Comment by cutterbl** [comment]
The 1.0.0 release does not bundle moment or moment-timezone
