### ISSUE TITLE
Adjusting column widths according to the contents in day cell

### ISSUE THREAD

**Issue by sarikaya** [intljusticemission/react-big-calendar#1152]
#### Do you want to request a _feature_ or report a _bug_?
feature
#### What's the current behavior?
In month view, when a big size renderable object like `table` inserted to day cell via `titleAccessor`, it does not fit in day cell because of having flex size columns

https://codesandbox.io/s/w0n3nxx34w

![Image](https://i.ibb.co/LnzKH35/table.png)

#### What's the expected behavior?
Would be nice to have an option that adjust day of the week column widths according to the content size in day cell

**Comment by jquense** [comment]
We couldnt really support this well because a lot of layout of the component is based on assumptions that columns are equal widths. I would say that returning table or really any element from titleAccessor is not intended and likely to break in an upcoming release. The accesser props arent for controlling rendering, but I understand why folks do it we don't have a good alternative API for controlling the whole event

**Comment by paulhan221** [comment]
@jquense are there any plans to support this feature one day?

**Comment by zeeforce** [comment]
Is there an update

**Comment by zeeforce** [comment]
Hey man, I found a way you just

```
.rbc-events-container{
    width: 100%;
}
```
