### ISSUE TITLE
How can I have multiple dots on each date?

### ISSUE THREAD

**Issue by diamondback15** [intljusticemission/react-big-calendar#1156]
Hello, I need to have a dot for each event on each day of the month view. Right now I see there's a new row every time I add an event.

Can I make it looks like that?
<img width="688" alt="screen shot 2018-12-16 at 8 30 33 pm" src="https://user-images.githubusercontent.com/655531/50061843-7c4f1300-0171-11e9-984c-330551ea9ffe.png">

I'm not sure what to change in order to allow that.

**Comment by dmitrykrylov** [comment]
@diamondback15 hm, you can play with customizing css rules or components:
https://github.com/intljusticemission/react-big-calendar/blob/master/src/Calendar.js#L628

However, I think that `react-big-calendar` doesn't fit your purposes because month layout in 'react-big-calendar' is implemented in the way to have possibility of showing multiday events and therefore events are grouped by "index in the day" but not by the day.

**Comment by diamondback15** [comment]
Thanks for your answer. I did some research and the way days are built with segments without container is definitely a problem. I can make a workaround to append my dots inside the bg. I decided to use a basic calendar like this instead https://blog.flowandform.agency/create-a-custom-calendar-in-react-3df1bfd0b728
