### ISSUE TITLE
Fix onRangeChange not getting called when the value of the date prop changes

### ISSUE THREAD

**Issue by TomasHubelbauer** [intljusticemission/react-big-calendar#1208]
Right now it seems like the range change event is only getting called in the handlers `handleViewChange` and `handleNavigate`. I think when rendering with `date` which results to a different range, the event should be called as well. Probably also with `getNow`.

**Comment by sprietNathanael** [comment]
I think what should be called is the internal `handleNavigate`.
I'm trying to make a month calendar with a selectable date. I use `onSelectSlot` callback to update the `date` prop, but then `onNavigate` callback is not called, neither is `onRangeChange`. I need `onRangeChange` to be called because when setting an out-of-range date, it automatically changes the month.
If `handleNavigate` is called, it would call `onNavigate` and `handleRangeChange`, that will ultimately call `onRangeChange`.

**Comment by KrustyC** [comment]
Is there any reason why this is not going to be fixed? The API tell you that you should be able to use both `onNavigate` and `onRangeChange`, but neither of them is called. IS there a particular reason for this?

**Comment by TomasHubelbauer** [comment]
I think the development on this project has been stopped. I'm sure if you prepare a PR for this, the maintainer will merge it though. I worked around this for my use case and I hate stale bot so I just closed the issue when it was enabled on this repository, but it's still valid.
