### ISSUE TITLE
Show +_x_ more for allDay events in day view

### ISSUE THREAD

**Issue by junaidcs** [intljusticemission/react-big-calendar#1268]
Hello folks, is there a way to show `x_more` link in `day` view for `allDay` events?

#### What's the current behavior?

Currently its showing all `allDay` events (although can fix its height and add scroll)

#### What's the expected behavior?

It should show "x_more" link after displaying first `x` events. 

Thanks.

**Comment by jordanrolph** [comment]
I've wondered this too @junaidcs. We use the week view, and often have so many All Day events that the timed events are not visible. From reading the docs and issues I've not found a way to add '+ X more'.

My current workaround is similar to yours - adding scroll to the All Day area. For anyone interested, in Week view this is:

```
.rbc-allday-cell {
    border: 1px dotted hotpink;   /* for demo only  */
    overflow-y: scroll;
    max-height: 40vh;  /* amend height to suit your use case */
}
```

Also, for anyone using CSS modules, you can target rbc by using the selector `:global(.rbc-allday-cell) {/*styles*/}`

**Comment by jquense** [comment]
There isn't a way to do this, but the all-day events use the same component so it would be easy enough to make toggleable if someone wants to PR something

**Comment by zubko** [comment]
@jquense Hi, I'd like to make a PR with a toggle between modes for all day, but I can't find how to make all day for the Week view to display 'N more', like the Month view does. Can you give me a hint please?

**Comment by gbryan** [comment]
Thanks for the tip, @jordanrolph! For our case, targeting all of `.rbc-allday-cell` instead of just the content within it wasn't ideal since it results in the background color for the current day to be cut off:

![image](https://user-images.githubusercontent.com/1993853/113317636-6921cc00-92c4-11eb-8b56-2735a3073b6f.png)

We're instead targeting `.rbc-allday-cell .rbc-row-content`:

![image](https://user-images.githubusercontent.com/1993853/113317695-7c349c00-92c4-11eb-9ec8-de95aa9f57ba.png)
