### ISSUE TITLE
Event is extended once dragging starts

### ISSUE THREAD

**Issue by josephktcheung** [intljusticemission/react-big-calendar#1387]
#### Do you want to request a _feature_ or report a _bug_?
_bug_
#### What's the current behavior?

1. Clone `react-big-calendar`
2. Run `yarn` and `yarn examples`
3. Visit `http://localhost:3000/examples#dnd`
4. Drag the first event
5. Event end date is changed once we start dragging

![rbc-bug](https://user-images.githubusercontent.com/4270232/61165498-f99a0500-a553-11e9-8fb2-befcdad7b4e6.gif)

#### What's the expected behavior?

Event span should not be changed when it's being dragged.

This problem doesn't exist in v0.21.0 and is introduced in v0.22.0.

**Comment by Abror1997** [comment]
I have the same issue

**Comment by erald14** [comment]
same issue here

**Comment by alexseitsinger** [comment]
I'm having a similar issue: Each time a multi-day event is drag-and-drop'ed, its length is doubled, making the end-date incorrect.

**Comment by brmk** [comment]
@claytongroth we have found a workaround for this problem
https://github.com/UpLab/react-big-calendar
The problem is that this package relies on the date-arithmetic plugin of version 4.0.1 which has a significant bug in dates.add function when calculating the end date of the event on drag. The solution is to downgrade this dependency to 3.1.0.
you can use react-big-calendar: github:UpLab/react-big-calendar#master in your package.json for now

**Comment by brmk** [comment]
@alexseitsinger @josephktcheung @Abror1997 @erald14  we have found a workaround for this problem
https://github.com/UpLab/react-big-calendar
The problem is that this package relies on the date-arithmetic plugin of version 4.0.1 which has a significant bug in dates.add function when calculating the end date of the event on drag. The solution is to downgrade this dependency to 3.1.0.
you can use react-big-calendar: github:UpLab/react-big-calendar#master in your package.json for now
