### ISSUE TITLE
Going back from January to December will cause the calendar to jump two years back to October.

### ISSUE THREAD

**Issue by Sparragus** [intljusticemission/react-big-calendar#1389]
#### Do you want to request a _feature_ or report a _bug_?
Bug

#### What's the current behavior?
Move to January to any year. Then click the Back button to go to December of the year before. The calendar will instead jump to October of two years ago.

CodeSandbox: https://codesandbox.io/s/react-big-calendar-example-2m1df
Screencast: https://recordit.co/t92e8xKVGT
![](http://g.recordit.co/t92e8xKVGT.gif)

Browser:
Chrome 75
react-big-calendar 0.22.0

#### What's the expected behavior?
It should go to December of the year before.

#### Additional notes
This issue does not happen on `0.21.0`. See: https://codesandbox.io/s/react-big-calendar-example-osvhu

**Comment by Sparragus** [comment]
Thank you for making this project. I'm very grateful for it and for any help you can provide to resolve this issue. 🙏

**Comment by adoerler** [comment]
Hi,

I've experienced the very same problem.

Therefore I've checked what has been updated sinces v0.21

 => fix: use fixed date arithmetic lib and move bt-sass to devdep... see commit https://github.com/intljusticemission/react-big-calendar/commit/b223a61e4bb78f139373eb208e6225eea4b6a855

In fact there was a bug in the date-math component (see https://github.com/jquense/date-math/issues/17) which has been fixed in their 4.0.1 release.

Please make sure that you have this dependency on version 4.0.1!
It fixed the problem on my side.

Best regards
Andreas
