### ISSUE TITLE
BUG: Events grow onEventDrop in month view. 

### ISSUE THREAD

**Issue by claytongroth** [intljusticemission/react-big-calendar#1429]
#### Do you want to request a _feature_ or report a _bug_?
Bug
#### What's the current behavior?
Whenever I drag/move (not resize) an event in month-view. The event grows in duration by 81, 163, 327, 655 hours. 
Try moving the multi-day events in Month-view and observe the behavior.
https://codesandbox.io/s/react-big-calendar-022-event-growing-bug-8g4en

#### What's the expected behavior?
The multi day event should stay the same length even if moved to a new day.
Additionally, there is no drag/hover CSS showing as there is in examples with older versions. https://codesandbox.io/s/rsk8d

**Comment by brmk** [comment]
@claytongroth we have found a workaround for this problem
https://github.com/UpLab/react-big-calendar
The problem is that this package relies on the date-arithmetic plugin of version 4.0.1 which has a significant bug in `dates.add` function when calculating the end date of the event on drag. The solution is to downgrade this dependency to 3.1.0.
you can use `react-big-calendar: github:UpLab/react-big-calendar#master` in your package.json for now

**Comment by brmk** [comment]
related #1387

**Comment by claytongroth** [comment]
@brmk Thanks! Working perfectly!

**Comment by abdulahadd** [comment]
This solution doesnt work with react 18 and I'm still getting the problem
