### ISSUE TITLE
Disable truncating events in month view

### ISSUE THREAD

**Issue by thienanle** [intljusticemission/react-big-calendar#147]
Currently events truncate if there are more events than can fit the cell and "+x more" appears. I'd like a way to disable this, such as passing a boolean in as a prop.
![screen shot 2016-07-28 at 18 11 59](https://cloud.githubusercontent.com/assets/874402/17205581/e34d9be4-54ee-11e6-9247-42e353ac9a61.png)

**Comment by jquense** [comment]
not sure disabling it makes sense, what would you do with the events that don't fit?

**Comment by thienanle** [comment]
@jquense Our calendar API limits events to 2 per day. If there are more than 2, a third event is returned with the title set to the number of additional events.

**Comment by bluespore** [comment]
@jquense I think the feature @thienanle proposes makes sense. 

Currently RBC assumes the *entirety* of event data will be passed for the given month, and it takes the truncating logic into it's own hands. In an instance where an API has specifically been developed to truncate the day summaries in favour of a separate API call for the day detail (maybe for performance, maybe because there's a lot more information required on that applications detail view pane?) RBC makes this difficult.

If we introduced a boolean `truncateEvents` prop, we could opt-out of the default functionality that already exists, and allow users to create richer experiences with the calendar.

**Comment by bluespore** [comment]
I've created a PR which solves the problem if you'd like to take a look @jquense https://github.com/intljusticemission/react-big-calendar/pull/151

**Comment by masull** [comment]
Many events (say, 10+) in the same time slot can be difficult to display.  Full Calendar handles more events than can fit in a cell by expanding the entire week row on the monthly view.  The week and day view have an option to turn off the time slots, essentially, displaying the full day view.  In this case, the times are not attached to the event array for the day and week. Both views work well with many events.

**Comment by dkniffin** [comment]
@jquense Sorry to bring up this old issue, but I'm running into the same thing. I'd like to display more than three events in a day. Is this possible currently? It looks like Full Calendar has a "eventLimit" option, which dictates the number of events displayed in a day. Could we use an option like that to control the cut-off point in showing "+X more"?

**Comment by jquense** [comment]
@dkniffin this have been discussed a lot over multiple issues, i'm open to a PR but it's not as simple as a toggle. you need to make large css changes. Please do go for it if you want, but i'd suggest search for the other issues detailing possible approaches

**Comment by zaach** [comment]
Can anyone point to the relevant past issues? I've only found ones that also suggest to do more searching.
