### ISSUE TITLE
Support others date format in events

### ISSUE THREAD

**Issue by rmdort** [intljusticemission/react-big-calendar#22]
In events.js, i noticed that you only support `"start": new Date(2015, 3, 0)` as the date format. 

Does bigcalendar support other date formats for start and end date? How can i achieve something of this format

`start: '2015-12-01-09:30AM'`

**Comment by jquense** [comment]
It doesn't support anything that isn't an actual `Date`. Generally speaking, parsing server responses is  outside the scope of this component, which tries to be as agnostic as possible about your data formats.  We think this makes sense anyway since your application will want to handle fetching, parsing, and caching with a more robust holistic approach across your application. We also want to make sure that the user has the opportunity to optimize that step as much as possible, when dealing with thousands or tens of thousands of events.

Not to mention that parsing dates is notoriously fraught and domain specific outside the few ISO formats (even still that can be a nightmare). In terms of getting hte work done though I recommend
- https://github.com/csnover/js-iso8601 for simple, straightforward date only parsing
- for a more robust solution we use https://github.com/jquense/yup, which is one of many options in js schema parsing libs
