### ISSUE TITLE
Adjusting how event cells are placed in the calendar day view.

### ISSUE THREAD

**Issue by JustinJKlein** [intljusticemission/react-big-calendar#276]
Hi all. 
I am hoping someone can help me with adjusting how events are placed in the day view of the calendar. I would like to have the events stack on top each other just as the time interval cells do. In fact if it used those for positioning that would be fantastic (nesting inside the timeslots as an element using display: block). Currently the event cells are dropped over the whole day view and are absolutely positioned from some sort of method. This causes event cell overlap  especially when you have events in the same timeslots. If anyone has any ideas about how to best change the positioning to get the desired effect that would be a big help.

Thanks in advance

**Comment by jquense** [comment]
the positioning logic isn't exposed or adjustable. I'm sure what you are asking for here, tho as stacking events on top of each other is impossible unless you have events with no overlapping times. The logic tho for positioning has just been made better in #269 so that may solve some of your issues. Otherwise tho there is always going to be some tradeoff in the strategy used to display events.
