### ISSUE TITLE
Can the week start on Monday instead of Sunday?

### ISSUE THREAD

**Issue by rmdort** [intljusticemission/react-big-calendar#28]
Example:

![image](https://cloud.githubusercontent.com/assets/118231/12346011/1bd9698c-bb8b-11e5-9233-3ff24db1f78a.png)

Can it start on monday?

**Comment by jquense** [comment]
you can, the start of the week is determined by the localizer. when using the included ones the week will start at the appropriate day for the chosen culture. 

if you want to change it yourself to something non standard for a culture {such as always setting it to monday) you can look at how localizer work, and edit/create your own since they are pluggable

**Comment by mtt87** [comment]
I'm not sure but this seems that it's not working anymore and there is a bit of inconsistency from docs and github repo.

In the docs http://intljusticemission.github.io/react-big-calendar/examples/index.html#intro

```js
import BigCalendar from 'react-big-calendar';
import moment from 'moment';

// Setup the localizer by providing the moment (or globalize) Object
// to the correct localizer.
BigCalendar.momentLocalizer(moment); // or globalizeLocalizer
```

I tried this also with `moment.locale('en-GB')` before passing the object.

Then I checked the master repo and seems different:
```js
BigCalendar.setLocalizer(
  BigCalendar.momentLocalizer(moment)
);
```

Both of them are not working for me anyway, the week is always starting on Sunday when it's supposed to start on Monday.
