### ISSUE TITLE
About event accuracy and overlap

### ISSUE THREAD

**Issue by niconchow** [intljusticemission/react-big-calendar#378]
I don‘t know why.The event's time is **inaccuracy**.They have a **deviation**!
And I want to set the event in hot pursuit.But the events are overlap.
![2](https://cloud.githubusercontent.com/assets/18158336/25689187/48a7f3a4-30b8-11e7-8978-a23f59b32aad.jpg)

**Comment by niconchow** [comment]
@jquense can you tell me the reason? thanks!

**Comment by jquense** [comment]
What? Sorry I don't understand what you're asking

**Comment by niconchow** [comment]
@jquense  The position is offset.I don't know what effect
![1](https://cloud.githubusercontent.com/assets/18158336/25689871/4a14e458-30be-11e7-84e6-c5aad746cb91.jpg)

**Comment by niconchow** [comment]
The startTime and endTime are inaccuracy.
If the two events are similar, they shrink, and I don't want that effect.
I want them not to shrink.
![2](https://cloud.githubusercontent.com/assets/18158336/25692148/fbc917fa-30d2-11e7-9cab-440986e97648.jpg)

**Comment by jquense** [comment]
The overlap because technically the events overlap, in that the end of eventA is the same as the start of eventB. I agree it probably shouldn't do that tho in this case.

**Comment by bkniffler** [comment]
I agree too, when an event ends at the exact same time another starts, its not really overlapping.

**Comment by jquense** [comment]
PR's Welcome :) should be easy enough to address

**Comment by bkniffler** [comment]
Okay, https://github.com/intljusticemission/react-big-calendar/pull/379 works for my overlaps. But I don't know if its right for you, please check @jquense

**Comment by tobiasandersen** [comment]
I remember working on this, and in the end went with something similar to what Google Calendar have. I believe they consider events overlapping if they end/start within < 15 minutes. I guess the reason being that your events could really blur together into one big mass if you have a lot of them (which we do). 

I know there was a discussion, in some issue or PR, about making the layout algorithm pluggable. Not sure whether that's a good idea or not, but people seem to want different things here, and that would be a way to address that.

**Comment by bkniffler** [comment]
I don't really agree to events ending up blurring into each other, since you can separate them by the borders already. The big issue here is that in some scenarios, overlaps need to be avoided, and by showing events that do not really overlap the same same way like overlapping events, you are confusing the users and you are making it harder to really make them aware of overlaps. 

And of course, if you have a lot of events, the resulting calendar will look all over the place.

If you don't want this by default, can we at least have some switch?

**Comment by niconchow** [comment]
The event A is going to be the same as the event B starts at the beginning, and they'll contract.
I don't want it to do that.
Can I do this ?
When the event A is going to be the same as the event B starts at the beginning, they don't influence each other.
![2](https://cloud.githubusercontent.com/assets/18158336/25731233/0170dda6-3177-11e7-9085-628a1ee13bec.jpg)

**Comment by tobiasandersen** [comment]
@bkniffler yeah I can see where you're coming from as well. Personally I don't really care that much, I just went with Google's solution because I assumed they had thought about it. 

I can mostly see two things people might want to change: what's discussed here, and what's discussed in https://github.com/intljusticemission/react-big-calendar/pull/341. One solution, as mentioned before, is to make the whole algorithm pluggable. Another would be to add something similar to the eventPropGetter (or maybe just adding more to that one), where these things could be overwritten.

**Comment by bkniffler** [comment]
My preferred solution to this would be to introduce an overlap mode prop. We could have 3 modes [none, intersect, soft/google]. This could also be represented as integer value (-1/false=none, 0=intersect, >=1=soft with the value used as tolerance, 60 would be the equivalent to the current behavior). The intersect mode should be default in my opinion. After thinking about this for some time, I can't imagine people would need to customize the behavior much more, so I see no added value in making this overwritable.

Whats discussed in #341 could be kind of a low-level solution for the basic issue that we got here, so I'd prefer something easier to use.

**Comment by tobiasandersen** [comment]
Sorry, I'm not sure I follow entirely. To me, there are two things to consider: 

1. When are two events considered siblings? As mentioned before, Google consider them siblings if the difference between their start and end is less than 15 minutes.  

2. Once two events are considered siblings, how much should they be allowed to overlap and grow?
 Just to make it clear what I'm talking about: If there are two siblings, they will each initially be given 50% of the space. If we stop here, the overlap would be 0 and the events would have the same width, and don't touch each other at all. But currently, we don't stop here. We allow the events to first grow by 30%, and then be moved to the left by the same amount. This is what causes the events to visually overlap.

Did you mean that we just skip point 2 above? Or could you clarify how this would work with your proposed solution?

**Comment by bkniffler** [comment]
Oh, just to correct myself, I meant 15 instead of 60 in my post.

Thanks for the explanation, I get how the siblings mechanism works. I don't personally use google calendar, but looking a screenshots ([1](https://lh6.googleusercontent.com/I6XtkmWlsnSm4iUMZkbPfEGADEA2QDNdPSOHjS7FGylg0zdK8HJhDKy5fpnyjU6aMrgNhFK3=s640-h400-e365), [2](https://matthewroyal.com/blog/wp-content/uploads/2014/09/Screen-Shot-2014-09-10-at-12.25.14-AM.png)), I don't find that there is this kind of behavior (+15 minutes tolerance between start/end of events to consider them overlapping).

I think that events should only be siblings, if there really is an intersection between start/end of events by default. My proposition was to implement this (which is what my PR does) and additionally to allow for no check on intersection (no events will ever be siblings) and to allow defining a tolerance value to have the current big-calendars behavior (15 minutes, 30 minutes, whatever), since I suppose you wouldn't want to completely remove it.

Hope I could clarify what I mean :)

**Comment by jquense** [comment]
I'd rather not make more things plugable if not necessary. In this case I think it's fine for events to not do the offset if they are exact matches for start/end on the initual slot. We **should** hoever adjust the default styling to provide some pixel spacing between the top and bottom of events like gcal does to avoid the issue of them blending together.

**Comment by bkniffler** [comment]
Could you merge the PR so we can get rid of the offsets? For the styling I see these options with the current markup: 
- Either reduce height by 0.5%
- Add white borders at the bottom
- No "white space" between events, just the dark borders to distinguish events

**Comment by greenya** [comment]
Hello.

Please tell me how to use old algorithm of drawing events (week and day views). My events a tightly aligned so when some ends - other exactly starts --- this is kind of class schedule, so it is possible to add events only in open windows (free time slots).

Now its all messed up, some goes normally, others are shifted.
Please see the image -- http://i.imgur.com/BWsz7vX.png -- Friday and Saturday got all events correctly placed (for some reason). I need all the events to be placed like that. It was fine until react-big-calendar update from couple of days ago.

**How can i specify the old method of event placement?**

Thank you.

**Comment by jquense** [comment]
> How can i specify the old method of event placement?

you can't. but you can write a PR that fixes the inconsistency

**Comment by bkniffler** [comment]
@greenya Its basically the same issue I was having. How does it look with the merged #379? Should be aligned cleanly now and no more problem.
