### ISSUE TITLE
Support for AMD module loader

### ISSUE THREAD

**Issue by AJDray** [intljusticemission/react-big-calendar#479]
I'm not a webpack user currently so having difficulty loading react-big-calendar into my project which uses AMD modules.

Could there be a build output which would support UMD?

**Comment by jquense** [comment]
Hi there, we aren't going to add a UMD build unfortunately. This project is intentionally forward looking in what it supports such asnot trying to work on browsers without flexbox or, now legacy formats like AMD and monolithic umd browser builds. I do realize folks may be stuck on older projects and tooling, but the cost to maintainers her to support these different things is significant especially since we don't need them so we've chosen to not support them here. Thanks!
