### ISSUE TITLE
How to use this module in a non-node environment

### ISSUE THREAD

**Issue by kuliraj** [intljusticemission/react-big-calendar#48]
Hi there,

This might be a bit of a silly question, but I've been struggling to get this up and running in a non-node environment. Basically I'm trying to get it running from inside of a WordPress website, but for that I'd need a compiled JS file that I can include. However I'd like to avoid having one file compiled with all dependencies(React, Lodash, etc.), since I'm already loading React from a separate file.

Is that even possible?

**Comment by jquense** [comment]
hi there, it is possible to some extent. We generally assume folks will be using a bundler like Browserify or Webpack to manage concating and bundling the modules together. We don't provide a "dist" build specifically which would have the module already built for just sticking in a browser script tag, since we don't have a use internally for it.

You can build such a file yourself, using these tools and the modules in the `/lib` folder which are compiled to commonJS modules and es5. I'd probably also take a PR that adds a build step to create a bundle if you are up for it
