### ISSUE TITLE
Mouseover event

### ISSUE THREAD

**Issue by gmarathi-nisum-com** [intljusticemission/react-big-calendar#538]
How to implement mouseover on a day event and to show the tooltip.

Thanks.

**Comment by nosnaj** [comment]
Refer to https://github.com/intljusticemission/react-big-calendar/blob/master/examples/demos/rendering.js

**Comment by TomasHubelbauer** [comment]
I am using the DnD addon. When I try to use the `event` component, it cannot capture the mouse events underneath the resize handles, the time range line and a few pixels off each side. I tried to use an event wrapper, but wrapping `props.children` in a `div` results in a zero-height div stacked at the top of the day column.

I am thinking that maybe instead of wrapping the children in the event wrapper, I could use `React.cloneElement` and assign the mouse handlers there, that way I should be able to get on `rbc-event` which is the whole area of the event. I will report back if that worked or not. Seems subpart though.

It would be cool if the event wrapper could be fixed so that is actually wraps the event element area, but the fix is probably not going to be trivial since `rbc-event` is absolutely positioned so it jumps out of the wrapper happily.

**Comment by TomasHubelbauer** [comment]
So turns out the above will break completely when actually dragging or resizing the event. I decided to prototype the `cloneElement` way and it works even when dragging and resizing, but my ultimate goal - to preselect slots on hover for the DnD actions to happen immediately and not after an event click, that I did not meet. I guess the DnD addon keeps its own state about what event is selected and just won;t start dragging/resizing even if the event is already selected without it being clicked once before the action.

```tsx
function BoundEventWrapperComponent(app: App) {
  return class EventWrapperComponent extends React.Component<EventWrapperProps, never> {
    public render() {
      const stockEventWrapper = React.Children.only(this.props.children) as React.ReactElement;
      const oldEventDiv = React.Children.only(stockEventWrapper.props.children) as React.ReactElement;
      const newEventDiv = React.cloneElement(oldEventDiv, { onMouseOver: this.onEventDivMouseOver });
      return React.cloneElement(stockEventWrapper, { children: newEventDiv });
    }
  
    private readonly onEventDivMouseOver: React.MouseEventHandler<HTMLDivElement> = _event => {
      app.setState({ selected: this.props.event });
    };
  };
}
```

**Comment by DanielShokri** [comment]
sds
