### ISSUE TITLE
Getting very slow

### ISSUE THREAD

**Issue by jcabrerazuniga** [intljusticemission/react-big-calendar#555]
Please, tell me what can make very slow React-BigCalendar? It is taking like a minute to show 20 events that occur within the same month
I am using:
                  <BigCalendar 
                             {...this.props}
                              selectable = {true}
                              formats={{dateFormat: 'dd', dayFormat:'dddd DD'}}
                              events={this.state.calendarEvents}
                               defaultView={'week'}
                                views={allViews}
						

                                defaultDate={new Date()}
                                 onSelectEvent={event => ...}
                                 onSelectSlot={(slotInfo) =>  ....................}
                                 eventPropGetter={(this.eventStyleGetter)}
                  />

I saw someone saying something about he startAccessor (issue #68) but no more explanations about what is startAccessor

**Comment by jquense** [comment]
It's really hard to diagnose perf issues since the can be really situation. I will so tho that I've used the calendar with hundreds of events in a month without performance issues, so I don't think its the component. Make sure you aren't doing unnecessary work like doing `new Date() ` in render() (cache the values you need)
