### ISSUE TITLE
slotPropGetter not called for TimeGrid

### ISSUE THREAD

**Issue by mx781** [intljusticemission/react-big-calendar#585]
Hello,

It seems that slotPropGetter is only called if I am in the week or day view. Is this intentional and I should be using something else to style the month view, or is it a missing feature that could use a PR?

**Comment by tobiasandersen** [comment]
Hi! The `slotPropGetter` is for **time slots** only. And since there're no time slots in the month view, it's never called there. You should be able to style your month view the way you like using [custom components](http://intljusticemission.github.io/react-big-calendar/examples/index.html#prop-components) though. Feel free to re-open if this is not enough for you!
