### ISSUE TITLE
Chrome, flexbox causes month, to not be shown

### ISSUE THREAD

**Issue by binnut** [intljusticemission/react-big-calendar#60]
On chrome v49, the use of flexbox causes the month and agenda views to dissapear.

**Comment by jquense** [comment]
I'm looking at the examples on Chrome 49 and everything seems just fine...any more details?

**Comment by gazab** [comment]
I also had problems with views disappearing on Chrome. I tracked it down to "flex: 1 1 0%" on the class .rbc-time-content (https://github.com/intljusticemission/react-big-calendar/blob/master/src/less/time-grid.less#L77)

The problem is that the version I got from npm has "flex: 1 1 *0*" (without percentage) instead which breaks the design on Chrome. The source looks fine and the example works fine though! Maybe some webpack or less issue?

**Comment by nwabdou85** [comment]
@gazab Hi, so how did you fixe it??, the same issue here
