### ISSUE TITLE
Events don't load on server side rendering

### ISSUE THREAD

**Issue by Agranom** [intljusticemission/react-big-calendar#639]
Hello. I use your lib with server side rendering (renderToString/renderToStaticMarkup from react-dom/server). But there's a problem, that events render after calendar is rendered. Why it doesn't render events with it?

**Comment by tobiasandersen** [comment]
How are you getting the events? Are you sure they're available when you first render it?

**Comment by jquense** [comment]
closing for staleness

**Comment by stuart-williams** [comment]
I'm seeing the same issue. I think it's related to calculating the size of a row to work out how many events to show before "view more" (https://github.com/intljusticemission/react-big-calendar/blob/08c24942e5aa0a7414c987ba1bcf10559f30b98a/src/DateContentRow.js#L161)

Could this be configurable so that events can be rendered server side?
