### ISSUE TITLE
in 'Month' view, how to customize events order within each day ?

### ISSUE THREAD

**Issue by Sharlaan** [intljusticemission/react-big-calendar#654]
Very nice component, great job !

I'm trying to integrate it for a project, but he needs to order events within each day based on different criterias than start/end times.

Is there any way to hack into the daily sorting logic for the 'Month' view ?

**Comment by jquense** [comment]
I'm not sure what that would look like...If you don't order them by time then they are just a stack of events what do you need a calendar for?

**Comment by Sharlaan** [comment]
We have a list of events for each day, each event featuring as well other custom params asked from the client. One day can house more than 100 events, so using the nice `popup` prop.  
Now, in the month view, the client wants a better overview within each day, in the way of coloring and mostly sorting events of interest on top of events list currently viewed day (in popup), this depending on some custom event props.
Coloring event's background depending on custom condition is not a problem, but sorting is.

We tried tricking RBC by inputting same day/time value in start/end props, then sort the inputted array of events with our own sorting logic. Sadly RBC ignores it ...

So how can we use a custom sorting logic in the popup and day containers in the Month view ?

**Comment by jquense** [comment]
gotcha, so no there isn't really any way to customize it right now. Part of the concern is that the sorting of events in the month view is fairly complicated in the general case. For you you seem to have no (or few) events that span multiple days. When they do cross days you need to think abut the layout of the week as a whole not just a single day, for instance you don't want a multiday event shown partly on monday and wednesday, but hidden in a popup on tuesday (if avoidable).

That said i'm open to making some amount of the sorting here pluggable, if you are comfortable handling all the edge cases yourself, and want to submit a PR :)

**Comment by jehartzog** [comment]
I gave a dirty example of how to do this [here](https://github.com/intljusticemission/react-big-calendar/issues/838#issuecomment-417783468). Sorry about not making a clever PR to make it pluggable, but that actually looks a bit tricky 😨 .

**Comment by omarTornaghi** [comment]
I think my use case is quite similar, I want to have a customized time grid in Week view. Instead of having a grid displaying and ordering event using time, i want a grid that order by "Priority" or a custom attribute in general.
I write an example:
[
{
"name": "EVENT1",
"dateStart": "01/01/2022",
"dateEnd": "01/01/2022",
"state": COMPLETED"
},
{
"name": "EVENT2",
"dateStart": "01/01/2022",
"dateEnd": "01/01/2022",
"state": TODO"
},
{
"name": "EVENT3",
"dateStart": "01/01/2022",
"dateEnd": "01/01/2022",
"state": TODO"
}
]
I want to display
                             |          01/01         |        02/01       |    03/01       |   ......................
COMPLETED    |        EVENT1       |                           |                      |   ......................
TODO                 |       EVENT2       |                           |                      |   ......................
                            |       EVENT3       |                           |                      |   ......................
is there a way to achive this?
