### ISSUE TITLE
Release a new version with changes since 0.17 ?

### ISSUE THREAD

**Issue by jdeniau** [intljusticemission/react-big-calendar#666]
Hi,

Is it possible to release a new version with all changes since 0.17 ?

There are quite a few improvements that can not be used for now. 😿 

Thank you !

**Comment by tobiasandersen** [comment]
There's nothing stopping you from using those new features. I'm sure there'll be a new release when Jason has the time and energy and feels like the time is right. 

Personally I never appreciate "issues" like these, since the only thing they can possibly achieve is to put pressure and add more stress on the maintainer. Please understand it's currently also a holiday for a lot of people.

**Comment by jdeniau** [comment]
Well sorry if my issue was too pushy or misunderstood.
I do not know what is the release policy of this package (each new feature
/ each month / when the main contributor has the time / etc. (and each
solution is perfectly valid if it is explained))

I was just saying that there were a lot of cool new feature since 0.17 and
I would live to know when it is gonna be in production.

I know that Jason put a lot of energy in the React ecosystem and I thank
him for this!

Le 3 janv. 2018 20:31, "Tobias Andersen" <notifications@github.com> a
écrit :

**Comment by wasabigeek** [comment]
Hi @tobiasandersen, genuine noob question here - when you say nothing is stopping us from using the new features, you mean we need to fork/download and build ourselves? I tried to do `npm install --save intljusticemission/react-big-calendar#0b2c2347efa8fe4fb77f7931634de9a8ee1362ac` (locked at a commit in an attempt to have a deterministic build), but that doesn't include the `lib` folder as in the npm package.

**Comment by tobiasandersen** [comment]
Forking and building yourself is definitely an option (maybe the easiest even). If you `npm install` like you did, you should get the src folder (are you sure it's not there?). The problem is that [it's looking for lib/index.js](https://github.com/intljusticemission/react-big-calendar/blob/master/package.json#L8), and the lib folder won't be there. You could work around that a few different ways (e.g. forking and changing it to look for src/index.js, or make an alias in webpack). You'd also have to setup the build steps required in your own config if you use the src files. There might be other ways as well that I don't know of.

I believe there're still some problems on master, and https://github.com/intljusticemission/react-big-calendar/pull/578 is about to get merged. But once that's done and master looks alright, I think a new release would make a lot of sense.
