### ISSUE TITLE
Add development branch

### ISSUE THREAD

**Issue by arecvlohe** [intljusticemission/react-big-calendar#689]
## Description

In an effort to reduce bugs in the master branch I propose creating a development branch in which we can merge changes into and test out functionality before merging with master. Then we can implement a release cycle that pushes changes on a weekly or monthly basis to the master branch once all the kinks in development have been worked out. This is the start of a discussion to put the feelers out and see what others think of this idea.

**Comment by jquense** [comment]
Sorry for the long gap here! I think ultimately a dev branch won't help much, compared to other possible improvements like better testing. I think the added complexity of keeping master and dev branches in sync is not worth the effort here.  especially since we aren't often in a situation where some feature is holding back bug fixes from being released, since new big features are added very very infrequently
