### ISSUE TITLE
Drag'n Drop external components

### ISSUE THREAD

**Issue by bionicvapourboy** [intljusticemission/react-big-calendar#712]
#### Feature request
It would be nice to have an example of a drag/drop from outside react-big-calendar in order to make possible to drag and drop elements (IE: contacts) external from calendar component.

#### Current behavior
There is no example of drag/drop items in the calendar from outside

#### Expected behavior?
Have at least one example of drag/drop from outside

**Comment by jquense** [comment]
Good idea! This should be possible with the current API since it's using react DnD but i'm not sure how to do it. The DnD addon is maintained and documented mostly by other folks in the community (since i don't use it) so someone would have have to contribute such an example. For now i'll close this tho since this isn't something i'll be working on myself thanks!

**Comment by francescocerri** [comment]
> @bionicvapourboy Here is an example on my repo https://github.com/Tim1023/react-scheduler-firebase. Hope it can help you

With the new version of react-big-calendar this doesn't work
