### ISSUE TITLE
onView event - should set date along with the view name

### ISSUE THREAD

**Issue by vasilevich** [intljusticemission/react-big-calendar#732]
#### Do you want to request a _feature_ or report a _bug_?
I believe this is a bug because there is no way of knowing what date was selected.
#### What's the current behavior?
when 
you click a date number in big calendar , onView is called, but there is no way to know which date number is selected
![image](https://user-images.githubusercontent.com/1217224/31667891-610b5c8c-b359-11e7-9f39-6c34763af9ad.png)

onView is fired with (view:string)

```
function onView(view:string){

// But how can we know the date that was clicked? (in this example 09

}
```

#### What's the expected behavior?
I expect to have another parameter in the onView function:
 OPTION 1:
```
function onView(view:string, date:Date){
// date should be the exact date that is currently shown in the view day.
}
```
OPTION 2:
```
function onView(view:string, startDate:Date,endDate:Date){
// startDate:Dateshould be the exact date(eg start of the day/week/month) that is currently shown in the view day.
// endDate be the exact date(eg end of the day/week/month) that is currently shown in the view day.

}
```

**Comment by jquense** [comment]
Changing the view and changing the date are two different actions, which is why you don't see them combined.  `onView` fires when the `view` value changes and `onNavigate` fires when the current `date` changes. You can coordinate between the two callbacks for the info you need, or use `onNavigate` since it's passed `view` as well (since it fires after) but to be honest, there is always the possibilty that value in `onNavigate` is stale, but it should work for most use cases.

**Comment by Abenezer** [comment]
but .. suppose we save endDate and startDate on some state,  then when we change only the view , how can we update the saved dates.. (unless we make a dummy navigate request by refreshing the date)

**Comment by Abenezer** [comment]
oh we can just save the current date and update endDate and startDate according to the selected view on 'onView' method ..
