### ISSUE TITLE
Visual customization

### ISSUE THREAD

**Issue by MathiasKandelborg** [intljusticemission/react-big-calendar#737]
#### What's the current behavior?

I want to be able to style the calendar, I've searched quite a bit a can't seem to find any documentation.

#### What's the expected behavior?

Be able to find some initial steps on how to style the calendar; some docs on which classes are good to change and maybe even a small overview of whats going on with the styles. 

One of the things I would like to style is the toolbar as I'd love to see some material design going on to match the rest of my app.
___
Am I able to use the calendar without the styles? This way I could provide them with the help of a _checklist of the styles to add_ to the calendar to become visual/usable?

I would love to help out, I just don't quite know where to start yet. 

P.S I really **_really_** enjoy using this calendar - It only took me a short amount of time to customize the localization to danish with moment.js and display some custom events. Thanks for making a great project that's such a breeze to use.

**Comment by jquense** [comment]
Thanks for the kind words! most of the styles are required that are included, but you are free to customize as you like. We provide the `less` files if you wnat to use a preprocesser, you can override the relevant variables and build your own stylesheet. Otherwise i'd just dive into what the css classes are on the calendar and tweak as you see fit 👍

**Comment by GideonFlynn** [comment]
Thanks for the quick answer. I'll dive in and get my hands dirty. :)
