### ISSUE TITLE
moment localizer ignores culture setting on time ranges

### ISSUE THREAD

**Issue by kromit** [intljusticemission/react-big-calendar#74]
See [Lines #15 #16 on moment.js](//github.com/intljusticemission/react-big-calendar/blob/master/src/localizers/moment.js#L15). 'h.mma' is always used and and always produces AM/PM regardless culture setting

**Comment by krokofant** [comment]
This issue is a bit annoying

**Comment by krokofant** [comment]
It seems like *LT* would work better than any other *h:mma* variation. *LT* is the localized format for time as specified in the [MomentJS docs](http://momentjs.com/docs/#/displaying/format/).

The localized version *L* is used in the *dateRangeFormat* method but not the *timeRangeFormat* which this issue is about.

Any downside to changing this?

**Comment by krokofant** [comment]
Without implementing the PR above one could apply the following formatters as a prop to the calendar:
```jsx
formats={{
  eventTimeRangeFormat: ({ start, end }, culture, localizer) => (
    `${localizer.format(start, "LT")} - ${localizer.format(end, "LT")}`
  ),
  agendaTimeRangeFormat: ({ start, end }, culture, localizer) => (
    `${localizer.format(start, "LT")} - ${localizer.format(end, "LT")}`
  )
}}
```

**Comment by pungggi** [comment]
Same as https://github.com/intljusticemission/react-big-calendar/issues/267
