### ISSUE TITLE
Add support to React Native

### ISSUE THREAD

**Issue by dorthwein** [intljusticemission/react-big-calendar#77]
Any interest or thoughts about porting this over to react-native or making it universal?  Possibly by using something like react-native-web https://github.com/necolas/react-native-web

I'd be willing to help with the transition if the maintainers were game.

**Comment by jquense** [comment]
I think that would be a tough task, as there is a lot of really DOM specific code in here. It'd also be tough to maintain since we'd have to keep up to date with the interop layer, while only really using the web version. I do like the idea in general, but I don't think it makes sense right now. 

Thanks for the offer to help though!

**Comment by pcooney10** [comment]
Hey - anyone ever give more thought to this / take a stab at implementing it?

**Comment by acro5piano** [comment]
https://github.com/llotheo/react-native-big-calendar
