### ISSUE TITLE
ResourceID not passed in onSelectSlot

### ISSUE THREAD

**Issue by npalansky** [intljusticemission/react-big-calendar#801]
#### onSelectSlot gets "resourceID: undefined"

- Can replicate by adding an onSelectSlot to the "resource" demo
let Resource = () => (
  <BigCalendar
    ...
   onSelectSlot={((slot) => console.log(slot))}
  />
)

**Comment by tanmay-cs13** [comment]
This issue is in the file TimeGrid.js. line no.: 189.
They are returning the resource.id so you get the resourceID in onSelectSlot only if you set the resourceIdAccessor as "id".

Well they have change the code and now they are reading the props in there latest code if you see in there repo: resource={get(resource, resourceIdAccessor)}

They merged it 3 days ago on master but still there latest code is not get in node_modules. You can see the code difference in there repo and the code present in node_modules. May be they didn't update their npm package yet.

**Comment by jquense** [comment]
we haven't released the fix yet, but yes it's been merged
