### ISSUE TITLE
Calendar removes all cells because date prop isn't set

### ISSUE THREAD

**Issue by nobobo1234** [intljusticemission/react-big-calendar#849]
#### Do you want to request a _feature_ or report a _bug_?
I want to request a bug

#### What's the current behavior?
When I first load my calendar the date property looks undefined. When I try to navigate between weeks/days it all turns blank. When I click the today button the date property gets a value and it all works again. And while I am talking, I always need to set the event container width to a 100% because somehow it isn't set to 100%

https://github.com/nobobo1234/reactplanner/blob/master/src/components/CalendarWrapper/CalendarWrapper.js Here is where I use the calendarWrapper

https://8n8kx9z6ll.codesandbox.io/ Here is an example

#### What's the expected behavior?
The expected behavior is that the date property is set from the beginning so that the page doesn't turn blank.

**Comment by eps1lon** [comment]
Can confirm. Not setting the `defaultDate` will set the `date` prop to `Invalid Date` when clicking `back` or `next`.

It should be documented that this property is required. Setting this to `now` in the component could trigger unnecessary rerenders because it would change every time the prop is passed. The user should decide when he sets `now` and how often this should change.

**Comment by arecvlohe** [comment]
Fixed in #889
