### ISSUE TITLE
Agenda View Empty (Month View showing)

### ISSUE THREAD

**Issue by xevix** [intljusticemission/react-big-calendar#859]
I've set the min-height for the calendar, and the month view is showing fine, but the agenda is empty. The events are being sent in via the `events` prop. Do I need to set them elsewhere for the agenda?

**Comment by xevix** [comment]
It looks like they're getting filtered out by the inRange call in Agenda renderDay method, even though these show up in month view. I'm using Moment for localization, nothing custom. The Events store start and end dates initialized from Moment objects made from Date objects made from strings of format 'YYYYMMDD' but with no time. Perhaps this is the issue?

**Comment by pl12133** [comment]
@xevix Have you taken a look at https://github.com/intljusticemission/react-big-calendar/pull/850#issuecomment-390738422? It sounds similar to your issue.

**Comment by xevix** [comment]
After a bit of digging, I found out a few things:
1. Start and End cannot be the same, or event gets filtered out. Kinda makes sense, but I wanted all-day events. Further dugging found an allDay property, so now using that (as well as ensuring start and end are different.

2. Agenda chose 30 days as the length to go back and forth clicking prev/next. This leads to different behavior than Month view, and is questionably useful. You can change the number of days, but not the type of period, so there's no way to change it to "1 month" at the moment. This is not great, but acceptable.

Since I got events starting to show via (1), closing this issue.

**Comment by AbeCole** [comment]
@xevix I'm having the same issue and the solutions don't seem to make 'proper' sense to me. I want allDay events and therefore they should have the same start and end date. The solution you used of changing the start & end dates to be different doesn't really work for me as then the events will stretch over 2 days rather than 1 day.

Only just started using react-big-calendar so not familar with it, possibly there is a different prop I can pass that allows us to make our own comparsion function that works correctly, anyone know?

**Comment by hermance** [comment]
I was blocked on this subject, and then clicked "next" of the calendar and here where my events.
 new Date(2020, 1, 27), => 27 feb 2020. The months are -1.
