### ISSUE TITLE
ERROR in ./node_modules/react-big-calendar/lib/css/react-big-calendar.css  Module build failed: TypeError: Cannot convert undefined or null to object 

### ISSUE THREAD

**Issue by Masroor69** [intljusticemission/react-big-calendar#868]
#i trying to build my React  Application with webPack ... . 

building Process end up with an error 
`ERROR in ./node_modules/react-big-calendar/lib/css/react-big-calendar.css (./node_modules/css-loader??ref--6-1!./node_modules/postcss-loader/lib!./node_modules/react-big-calendar/lib/css/react-big-calendar.css)
Module build failed: TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at load (/Users/MasroorHosseini/IdeaProjects/hospitalportalfrontend/node_modules/postcss-load-plugins/lib/plugins.js:42:38)
    at /Users/MasroorHosseini/IdeaProjects/hospitalportalfrontend/node_modules/postcss-load-plugins/lib/plugins.js:66:18
    at Array.forEach (<anonymous>)
    at plugins (/Users/MasroorHosseini/IdeaProjects/hospitalportalfrontend/node_modules/postcss-load-plugins/lib/plugins.js:65:8)
    at /Users/MasroorHosseini/IdeaProjects/hospitalportalfrontend/node_modules/postcss-load-config/index.js:64:18
    at <anonymous>
 @ ./node_modules/react-big-calendar/lib/css/react-big-calendar.css 2:14-127 21:1-42:3 21:125-42:2 22:19-132
 @ ./src/Component/Surgerie/EventCalender.js
 @ ./src/Component/Surgerie/Calender.js
 @ ./src/Component/MainNavigation.js
 @ ./src/Component/App.js
 @ ./src/Component/AppContiner.js
 @ ./src/index.js
`
i'm using  webPack to Build My Application so my **webpack.config.js**  file is the following:

`
const webpack = require('webpack');
const path = require('path');

const mode = process.env.NODE_ENV;

console.log('My MOde : ', mode);
module.exports = {
  target: 'web',
  mode,
  entry:
    './src/index.js',
  module: {
    rules: [
      {
        test: /\.(js|jsx)$/,
        use: 'babel-loader',
        exclude: /node_modules/,
        // query: {
        //   presets: ['es2015']
        // }
      },
      {
        test: /\.js$/,
        exclude: /node_modules/,
        use: ['babel-loader', 'eslint-loader']
      },
      {
        test: /\.css$/,
        use: [
          'style-loader',
          { loader: 'css-loader', options: { importLoaders: 1 } },
          'postcss-loader'
        ],
      }
    ]
  },
  resolve: {
    extensions: ['*', '.js', '.jsx'],
    modules: [
      path.resolve(__dirname, 'dist'),
      'node_modules'
    ],
  },
  output: {
    path: `${__dirname}/dist`,
    publicPath: '/',
    filename: 'bundle.js'
  },
  node: {
    console: true,
    fs: 'empty',
    net: 'empty',
    tls: 'empty'
  },
  plugins: [
    new webpack.HotModuleReplacementPlugin()
  ],
  devServer: {
    contentBase: './dist',
    hot: true,
    watchContentBase: true,
    compress: true,
  },
};
`
as  i use postcss-loader for loader of my Css File 
i use the configuration that they Provide in its repo 

`module.exports = ({ file, options, env }) => ({
  parser: file.extname === '.sss' ? 'sugarss' : false,
  plugins: {
    'postcss-import': { root: file.dirname },
    'postcss-cssnext': options.cssnext ? options.cssnext : false,
    'autoprefixer': env === 'production' ? options.autoprefixer : false,
    'cssnano': env === 'production' ? options.cssnano : false
  }
})`

 Note : Development Version is work just fine ..

**Comment by pl12133** [comment]
@Masroor69 I am not sure what's wrong, but your problem sounds a lot like https://github.com/michael-ciniawsky/postcss-load-plugins/issues/67.

As a workaround you may want to try setting the `options` for `postcss-loader` to `null` or `{}`.

**Comment by tobiasandersen** [comment]
Hi, I don't think is a problem with react-big-calendar, but rather with your webpack config. Unfortunately we can't provide support for that here, but if you still have problems, I'd suggest asking in the [Discord channel](https://discordapp.com/invite/uJsgpkC)!

**Comment by hwolf0610** [comment]
TypeError: Cannot read property 'filter' of undefined
eventsForWeek
E:/Github/React_Big_Calendar_only/node_modules/react-big-calendar/dist/react-big-calendar.esm.js:1816
  1813 | } : {};
  1814 | 
  1815 | var eventsForWeek = function eventsForWeek(evts, start, end, accessors) {
> 1816 |   return evts.filter(function (e) {
  1817 |     return inRange(e, start, end, accessors);
  1818 |   });
  1819 | };
View compiled
MonthView._this.renderWeek
E:/Github/React_Big_Calendar_only/node_modules/react-big-calendar/dist/react-big-calendar.esm.js:1854
  1851 | var _this$state = _this.state,
  1852 |     needLimitMeasure = _this$state.needLimitMeasure,
  1853 |     rowLimit = _this$state.rowLimit;
> 1854 | events = eventsForWeek(events, week[0], week[week.length - 1], accessors);
       | ^  1855 | events.sort(function (a, b) {
  1856 |   return sortEvents(a, b, accessors);
  1857 | });
View compiled
MonthView.render
E:/Github/React_Big_Calendar_only/node_modules/react-big-calendar/dist/react-big-calendar.esm.js:2031
  2028 |   this._weekCount = weeks.length;
  2029 |   return React.createElement("div", {
  2030 |     className: clsx('rbc-month-view', className)
> 2031 |   }, React.createElement("div", {
       | ^  2032 |     className: "rbc-row rbc-month-header"
  2033 |   }, this.renderHeaders(weeks[0])), weeks.map(this.renderWeek), this.props.popup && this.renderOverlay());
  2034 | };
View compiled
finishClassComponent
E:/Github/React_Big_Calendar_only/node_modules/react-dom/cjs/react-dom.development.js:18470
  18467 | } else {
  18468 |   {
  18469 |     setCurrentPhase('render');
> 18470 |     nextChildren = instance.render();
        | ^  18471 | 
  18472 |     if (debugRenderPhaseSideEffectsForStrictMode && workInProgress.mode & StrictMode) {
  18473 |       instance.render();
View compiled
updateClassComponent
E:/Github/React_Big_Calendar_only/node_modules/react-dom/cjs/react-dom.development.js:18423
  18420 |   shouldUpdate = updateClassInstance(current$$1, workInProgress, Component, nextProps, renderExpirationTime);
  18421 | }
  18422 | 
> 18423 | var nextUnitOfWork = finishClassComponent(current$$1, workInProgress, Component, shouldUpdate, hasContext, renderExpirationTime);
        | ^  18424 | 
  18425 | {
  18426 |   var inst = workInProgress.stateNode;
View compiled
beginWork$1
E:/Github/React_Big_Calendar_only/node_modules/react-dom/cjs/react-dom.development.js:20186
  20183 | 
  20184 |     var _resolvedProps = workInProgress.elementType === _Component2 ? _unresolvedProps : resolveDefaultProps(_Component2, _unresolvedProps);
  20185 | 
> 20186 |     return updateClassComponent(current$$1, workInProgress, _Component2, _resolvedProps, renderExpirationTime);
        | ^  20187 |   }
  20188 | 
  20189 | case HostRoot:
View compiled
HTMLUnknownElement.callCallback
E:/Github/React_Big_Calendar_only/node_modules/react-dom/cjs/react-dom.development.js:336
  333 |     window.event = windowEvent;
  334 |   }
  335 | 
> 336 |   func.apply(context, funcArgs);
      | ^  337 |   didError = false;
  338 | } // Create a global error event handler. We use this to capture the value
  339 | // that was thrown. It's possible that this error handler will fire more
View compiled
invokeGuardedCallbackDev
E:/Github/React_Big_Calendar_only/node_modules/react-dom/cjs/react-dom.development.js:385
  382 | // errors, it will trigger our global error handler.
  383 | 
  384 | evt.initEvent(evtType, false, false);
> 385 | fakeNode.dispatchEvent(evt);
      | ^  386 | 
  387 | if (windowEventDescriptor) {
  388 |   Object.defineProperty(window, 'event', windowEventDescriptor);
View compiled
invokeGuardedCallback
E:/Github/React_Big_Calendar_only/node_modules/react-dom/cjs/react-dom.development.js:440
  437 | function invokeGuardedCallback(name, func, context, a, b, c, d, e, f) {
  438 |   hasError = false;
  439 |   caughtError = null;
> 440 |   invokeGuardedCallbackImpl$1.apply(reporter, arguments);
  441 | }
  442 | /**
  443 |  * Same as invokeGuardedCallback, but instead of returning an error, it stores
View compiled
beginWork$$1
E:/Github/React_Big_Calendar_only/node_modules/react-dom/cjs/react-dom.development.js:25780
  25777 | } // Run beginWork again.
  25778 | 
  25779 | 
> 25780 | invokeGuardedCallback(null, beginWork$1, null, current$$1, unitOfWork, expirationTime);
        | ^  25781 | 
  25782 | if (hasCaughtError()) {
  25783 |   var replayError = clearCaughtError(); // `invokeGuardedCallback` sometimes sets an expando `_suppressLogging`.
View compiled
performUnitOfWork
E:/Github/React_Big_Calendar_only/node_modules/react-dom/cjs/react-dom.development.js:24698
  24695 |   next = beginWork$$1(current$$1, unitOfWork, renderExpirationTime);
  24696 |   stopProfilerTimerIfRunningAndRecordDelta(unitOfWork, true);
  24697 | } else {
> 24698 |   next = beginWork$$1(current$$1, unitOfWork, renderExpirationTime);
        | ^  24699 | }
  24700 | 
  24701 | resetCurrentFiber();
View compiled
workLoopSync
E:/Github/React_Big_Calendar_only/node_modules/react-dom/cjs/react-dom.development.js:24671
  24668 | function workLoopSync() {
  24669 |   // Already timed out, so perform work without checking if we need to yield.
  24670 |   while (workInProgress !== null) {
> 24671 |     workInProgress = performUnitOfWork(workInProgress);
  24672 |   }
  24673 | }
  24674 | /** @noinline */
View compiled
performSyncWorkOnRoot
E:/Github/React_Big_Calendar_only/node_modules/react-dom/cjs/react-dom.development.js:24270
  24267 | 
  24268 | do {
  24269 |   try {
> 24270 |     workLoopSync();
        | ^  24271 |     break;
  24272 |   } catch (thrownValue) {
  24273 |     handleError(root, thrownValue);
View compiled
scheduleUpdateOnFiber
E:/Github/React_Big_Calendar_only/node_modules/react-dom/cjs/react-dom.development.js:23698
  23695 |   // root inside of batchedUpdates should be synchronous, but layout updates
  23696 |   // should be deferred until the end of the batch.
  23697 | 
> 23698 |   performSyncWorkOnRoot(root);
        | ^  23699 | } else {
  23700 |   ensureRootIsScheduled(root);
  23701 |   schedulePendingInteractions(root, expirationTime);
View compiled
updateContainer
E:/Github/React_Big_Calendar_only/node_modules/react-dom/cjs/react-dom.development.js:27103
  27100 |   }
  27101 | 
  27102 |   enqueueUpdate(current$$1, update);
> 27103 |   scheduleWork(current$$1, expirationTime);
  27104 |   return expirationTime;
  27105 | }
  27106 | function getPublicRootInstance(container) {
View compiled
(anonymous function)
E:/Github/React_Big_Calendar_only/node_modules/react-dom/cjs/react-dom.development.js:27528
  27525 | 
  27526 | 
  27527 |   unbatchedUpdates(function () {
> 27528 |     updateContainer(children, fiberRoot, parentComponent, callback);
        | ^  27529 |   });
  27530 | } else {
  27531 |   fiberRoot = root._internalRoot;
View compiled
unbatchedUpdates
E:/Github/React_Big_Calendar_only/node_modules/react-dom/cjs/react-dom.development.js:24433
  24430 | executionContext |= LegacyUnbatchedContext;
  24431 | 
  24432 | try {
> 24433 |   return fn(a);
        | ^  24434 | } finally {
  24435 |   executionContext = prevExecutionContext;
  24436 | 
View compiled
legacyRenderSubtreeIntoContainer
E:/Github/React_Big_Calendar_only/node_modules/react-dom/cjs/react-dom.development.js:27527
  27524 |   } // Initial mount should not be batched.
  27525 | 
  27526 | 
> 27527 |   unbatchedUpdates(function () {
        | ^  27528 |     updateContainer(children, fiberRoot, parentComponent, callback);
  27529 |   });
  27530 | } else {
View compiled
render
E:/Github/React_Big_Calendar_only/node_modules/react-dom/cjs/react-dom.development.js:27608
  27605 |     }
  27606 |   }
  27607 | 
> 27608 |   return legacyRenderSubtreeIntoContainer(null, element, container, false, callback);
  27609 | }
  27610 | function unstable_renderSubtreeIntoContainer(parentComponent, element, containerNode, callback) {
  27611 |   if (!isValidContainer(containerNode)) {
View compiled
Module../src/index.js
E:/Github/React_Big_Calendar_only/src/index.js:33
  30 |         </div>
  31 |     </Router>
  32 | )
> 33 | ReactDOM.render(routing, document.getElementById('root'));  
  34 | 
  35 | 
View compiled
__webpack_require__
E:/Github/React_Big_Calendar_only/webpack/bootstrap:785
  782 | };
  783 | 
  784 | // Execute the module function
> 785 | modules[moduleId].call(module.exports, module, module.exports, hotCreateRequire(moduleId));
      | ^  786 | 
  787 | // Flag the module as loaded
  788 | module.l = true;
View compiled
fn
E:/Github/React_Big_Calendar_only/webpack/bootstrap:150
  147 | 		);
  148 | 		hotCurrentParents = [];
  149 | 	}
> 150 | 	return __webpack_require__(request);
      | ^  151 | };
  152 | var ObjectFactory = function ObjectFactory(name) {
  153 | 	return {
View compiled
1
http://localhost:3000/static/js/main.chunk.js:815:18
__webpack_require__
E:/Github/React_Big_Calendar_only/webpack/bootstrap:785
  782 | };
  783 | 
  784 | // Execute the module function
> 785 | modules[moduleId].call(module.exports, module, module.exports, hotCreateRequire(moduleId));
      | ^  786 | 
  787 | // Flag the module as loaded
  788 | module.l = true;
View compiled
checkDeferredModules
E:/Github/React_Big_Calendar_only/webpack/bootstrap:45
  42 | 	}
  43 | 	if(fulfilled) {
  44 | 		deferredModules.splice(i--, 1);
> 45 | 		result = __webpack_require__(__webpack_require__.s = deferredModule[0]);
     | ^  46 | 	}
  47 | }
  48 | 
View compiled
Array.webpackJsonpCallback [as push]
E:/Github/React_Big_Calendar_only/webpack/bootstrap:32
  29 | 	deferredModules.push.apply(deferredModules, executeModules || []);
  30 | 
  31 | 	// run deferred modules when all chunks ready
> 32 | 	return checkDeferredModules();
     | ^  33 | };
  34 | function checkDeferredModules() {
  35 | 	var result;




I can see this error.

Please help me.

ASAP
