### ISSUE TITLE
Drag and drop an event from one month to another

### ISSUE THREAD

**Issue by rmanalan** [intljusticemission/react-big-calendar#887]
#### Do you want to request a _feature_ or report a _bug_?
Feature

#### What's the current behavior?
I'd like to be able to drag and drop an event from one month to the next. This doesn't seem to be possible.

**Comment by arecvlohe** [comment]
@rmanalan Can you create an example using codesandbox? You should already be able to do this.

**Comment by arecvlohe** [comment]
This seems more like a bug if you are not able to do this already

**Comment by rmanalan** [comment]
@arecvlohe here you go https://codesandbox.io/s/m5vr0wq5ox

The current version of `react-big-calendar` only allows you to drag and drop to a visible day on the month view. It would be great if there was a hot zone that could allow a user to initiate a next or previous navigation while dragging.

**Comment by jquense** [comment]
yeah that isn't currently possible but I think we'd be more than open to making it so, if someone wants to work on it. I'd be interested what other solutions do for this.

**Comment by ehahn9** [comment]
+1 for this excellent enhancement. Just for completeness (these might be YAGNI cases!):

* this would ideally work for any view (e.g. in day view, you could drop an event on days in the future or past). Not sure of what it means in each case, tho. BTW, I punted on DnD for agenda view altogether.

* I presume we would issue `onNavigate` (sort of like the toolbar does). Would need to think through what this means for controlled instances?

* If navigation has occurred, not exactly sure what happens if the user abandons the dnd explicitly (esc) or implicitly (invalid drop target): do we scroll back to where they started or stay at the scrolled-to date?

I hope these comments don't dissuade anyone from tackling this! It would be a wonderful addition, IMO!

**Comment by arecvlohe** [comment]
@ehahn9 I agree, seems like a nice enhancement. In the project I am working on, I modified RBC to render a two month view to move things around from the current month to the next.

**Comment by rmanalan** [comment]
PR here... looking for feedback. Thx! #896
