### ISSUE TITLE
Import localizer module on demand

### ISSUE THREAD

**Issue by ilovepumpkin** [intljusticemission/react-big-calendar#898]
#### Do you want to request a _feature_ or report a _bug_?
maybe this is a feature or just a question, since many packages support "import on demand".

#### What's the current behavior?
I am using moment with big calendar, but now in the bundle file, I can still see globalize.js and oldGlobalize.js. 

#### What's the expected behavior?
Since I just need to use moment, I hope only import moment related code.

The reason why I ask this is because our security team reports there is XSS issue in oldGlobalize.js. If I could exclude this, I could continue using react-big-calendar, otherwise I have to choose other alternatives.  I am still not sure if this XSS issue is reported by mistake or not since snyk does not say there is any issues -  [https://github.ibm.com/IBM-IOTM/PO/issues/url](url)   . No matter what "import on demand" is an good improvement, :), agree?

**Comment by arecvlohe** [comment]
@ilovepumpkin I am not sure how you are getting globalize into your bundle other than if you are using it somewhere. Or, you probably need to remove it from your node_modules. I will close this for now since I don't think this is an issue with rbc but more an issue with how you are managing your dependencies.
