### ISSUE TITLE
Timeslot range change leads to selection bug?

### ISSUE THREAD

**Issue by rafsoaken** [intljusticemission/react-big-calendar#9]
Setting the `min` and `max` props in the Calendar Component (two Date values specifying a starting time and ending time) nicely limit the displayed time range in the Week and Day Views. 

I.e. using 
    min={new Date(2015, 10, 19, 8, 0, 0)}
    max={new Date(2015, 10, 19, 21, 0, 0)}

limits the TimeGutter to display only the hours from 08:00 AM to 21:00 PM.
Unfortunately the time properties of the event passed to any onSelectSlot / onSelectEvent handlers now have messed up start and end times. These times seem to still assume a timegrid going from 00:00 to 24:00. Dragging the selection is even worse as now slots light up in a reverse(?) order and start and end times are set to 00:00.

Should this work, should I do something else or is this unsupported behaviour?
Thanks

**Comment by pastachan** [comment]
I have the same problem when changing the min and max props. The .rbc-slot-selection element styles become inaccurate when the hour ranges of the day are changed.

**Comment by jquense** [comment]
hey everyone, defiantely looks like a bug, DaySlot seems to just not be testing against min/max. Annoying oversight. If someone is really anxious to get this fixed as quick as possible feel free to submit a PR, otherwise I will definately address it, just not sure that will happen by next week (holiday week so I am going to be traveling/with family for most of it)
