### ISSUE TITLE
Show more calculation seems to be off

### ISSUE THREAD

**Issue by craig-day** [intljusticemission/react-big-calendar#92]
When passing in a custom event component for the month view, and using the popup option, the calculation of when to display the show more option seems to be a little off.  

![](http://content.screencast.com/users/CDay.zendesk/folders/Jing/media/55c4a908-c041-4221-a471-a77c2aeeede1/00000213.png)

The option should be displayed when there are more than two events in this case, but doesn't get displayed until there are more than three meaning the third event gets cut off.

**Comment by jquense** [comment]
The way the calculation is made is that the calendar will render a "fake" event with the `rbc-event` and `rbc-event-content` classes with essentially empty content and measure that. The implicit assumption is that most styling of events will be done on those two classes, such that sticking them in the DOM will give a good enough height for all events. 

Admittedly this is not a foolproof method, but its about as god as you can get without laying out every event, measuring, and re-rendering. You also can't progressively render events and then "cut them off once they outgrow the space because each cell relates and affects the cells around it.

In your case you can fix the issue adding a fixed height to the event class so that the calendar will measure correctly, i'd also accept a PR that allows specifying event height as prop if you are so inclined

**Comment by craig-day** [comment]
Thanks for the super fast response! That definitely fixed it.  Maybe I'll work on event height as a prop, but this fixed it for me.
