### ISSUE TITLE
Showmore wrong render in month view

### ISSUE THREAD

**Issue by Mostafasaffari** [intljusticemission/react-big-calendar#982]
Hi
When I have lots of  events in many days show more render wrong.
![ren](https://user-images.githubusercontent.com/16894665/45251633-afa62880-b35e-11e8-9efa-f2ec6c8fb2d2.png)

**Comment by Mostafasaffari** [comment]
I solved it
you should change this line 
https://github.com/intljusticemission/react-big-calendar/blob/d1e90b148a0be2b71f2c1887b196cf5df088535c/src/EventRowMixin.js#L61

to 
var currentSlots = slots.slots ? slots.slots : slots;
var per = Math.abs(len) / currentSlots * 100 + '%';

and after that everything is OK :)

**Comment by riyazbhanvadia** [comment]
Hi @Mostafasaffari ,

do you have any idea how to ahicve this

What's the current behavior?
Current the events are rendered in a blue box from start to end Date.

What's the expected behavior?
I want to change how Events Are Rendered in each cell.
If anybody has seen how google calendar is rendering events in latest version.
They show each event in each date cell.
I want to extend that functionality and I tried to overload eventWrapper which you can see in the below sandbox :

https://codesandbox.io/s/94rrr34r9r

It only adds event in the start position of the row or date cell.

if you need any clarification please ask . Please refer to the sandbox also. All ideas are welcome . Thanks in advance

**Comment by Mostafasaffari** [comment]
Hi
To be honest I don't get it. You mean for example "Some title 3" in today become red and this event in the end of event will be blue.
If you could possibly please draw a wire-frame or mockup which you want.
