### ISSUE TITLE
Bug 🐞: min + max props breaks layout.

### ISSUE THREAD

**Issue by karltaylor** [intljusticemission/react-big-calendar#999]
#### Do you want to request a _feature_ or report a _bug_?

Bug

#### What's the current behavior?

Passing `min` and `max` props breaks the position of events.

https://codesandbox.io/s/14jq64y553

![screen shot 2018-09-23 at 14 02 57](https://user-images.githubusercontent.com/6763109/45928309-6c8cad80-bf39-11e8-8d52-ebf1bf855087.png)

#### What's the expected behavior?

Events to be in the correct position.

**Comment by dmitrykrylov** [comment]
I created a pull request to fix this issue

**Comment by janb87** [comment]
You have to deduct one minute (eg 17:59 if you want 18:00).

This piece of code is causing it (but I think it is by design, 0:00 -> 23:59).
https://github.com/intljusticemission/react-big-calendar/blob/master/src/utils/TimeSlots.js#L14
1 minute is added to totalMin var. A little bit further the numGroups is calculated and the number is rounded to the top (Math.ceil).
